baseURL = "https://keonhoban.github.io/mlops-journey/"
languageCode = "ko"
title = "ğŸ”ï¸  MLOps Journey"
theme = "PaperMod"

[params]
  ShowReadingTime = true
  defaultTheme = "auto"
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  categories = ["Linux", "Network", "AWS", "Python"]

  [params.assets]
    customCSS = ["css/custom.css"]

  [params.footer]
    hideCopyright = true
    customText = "Â© 2025 Keonho Ban | <a href=\"https://github.com/keonhoban\" target=\"_blank\">GitHub</a> | <a href=\"mailto:keonho0510@naver.com\">Email</a>"

[menu]

  [[menu.main]]
  name = "ğŸ  Home"
  url = "/"
  weight = 1

  [[menu.main]]
  name = "ğŸ“‚ Projects"
  url = "/projects/"
  weight = 2

  [[menu.main]]
  name = "ğŸ“ Blog"
  url = "/posts/"
  weight = 3

  [[menu.main]]
  name = "ğŸ§— About"
  url = "/about/"
  weight = 4

  [[menu.main]]
  name = "ğŸ“– Categories"
  url = "/categories/"
  weight = 5

